"""watchers

Revision ID: 38de6e070685
Revises: 983f20e4c0d9
Create Date: 2020-08-31 21:34:23.534738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38de6e070685'
down_revision = '983f20e4c0d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'watchers',
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False
        ),
        sa.Column('address', sa.String(length=128), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('alias', sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint('address'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchers')
    # ### end Alembic commands ###
