"""add last tx

Revision ID: 478b7eb4081b
Revises: c7dc1add7f81
Create Date: 2020-08-25 19:28:59.635265

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '478b7eb4081b'
down_revision = 'c7dc1add7f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hodlers', sa.Column('last_transaction', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hodlers', 'last_transaction')
    # ### end Alembic commands ###
