"""DecimalTotalSupply

Revision ID: 7a2bcf2b3f15
Revises: 478b7eb4081b
Create Date: 2020-08-25 23:36:09.051613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a2bcf2b3f15'
down_revision = '478b7eb4081b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('decimal', sa.Integer(), nullable=False))
    op.add_column('tokens', sa.Column('total_supply', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'total_supply')
    op.drop_column('tokens', 'decimal')
    # ### end Alembic commands ###
