"""TokenURLs

Revision ID: 983f20e4c0d9
Revises: 787c36ff6dc8
Create Date: 2020-08-30 14:54:15.625959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983f20e4c0d9'
down_revision = '787c36ff6dc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('coingecko_url', sa.String(length=320), nullable=True))
    op.add_column('tokens', sa.Column('logo_url', sa.String(length=320), nullable=True))
    op.add_column('tokens', sa.Column('telegram_url', sa.String(length=320), nullable=True))
    op.add_column('tokens', sa.Column('twitter_url', sa.String(length=320), nullable=True))
    op.add_column('tokens', sa.Column('watchlist_addresses', sa.String(length=3200), nullable=True))
    op.add_column('tokens', sa.Column('website_url', sa.String(length=320), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'website_url')
    op.drop_column('tokens', 'watchlist_addresses')
    op.drop_column('tokens', 'twitter_url')
    op.drop_column('tokens', 'telegram_url')
    op.drop_column('tokens', 'logo_url')
    op.drop_column('tokens', 'coingecko_url')
    # ### end Alembic commands ###
