"""TokenHodlersTranfers

Revision ID: e552f21b0ae5
Revises: 
Create Date: 2020-08-22 22:46:15.922525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e552f21b0ae5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tokens',
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False
        ),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('contract_address', sa.String(length=128), nullable=False),
        sa.Column('uniswap_address', sa.String(length=128), nullable=False),
        sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('synced', sa.Boolean(), nullable=False),
        sa.Column('last_block', sa.Integer(), nullable=True),
        sa.Column('block_creation', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('name'),
        sa.UniqueConstraint('contract_address'),
    )
    op.create_table(
        'hodlers',
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False
        ),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('address', sa.String(length=128), nullable=False),
        sa.Column('number_transactions', sa.Integer(), nullable=True),
        sa.Column('amount', sa.String(length=64), nullable=False),
        sa.Column('token_name', sa.String(length=8), nullable=True),
        sa.ForeignKeyConstraint(['token_name'], ['tokens.name'],),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_hodlers_address'), 'hodlers', ['address'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hodlers_address'), table_name='hodlers')
    op.drop_table('hodlers')
    op.drop_table('tokens')
    # ### end Alembic commands ###
