"""TokenHodlersTranfers

Revision ID: e667b4e25424
Revises:
Create Date: 2020-08-22 13:30:07.020872

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e667b4e25424'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'hodlers',
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False
        ),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('address', sa.String(length=128), nullable=False),
        sa.Column('number_transactions', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_hodlers_address'), 'hodlers', ['address'], unique=True)
    op.create_table(
        'tokens',
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False
        ),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('contract_address', sa.String(length=128), nullable=False),
        sa.Column('uniswap_address', sa.String(length=128), nullable=False),
        sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('last_block', sa.String(length=128), nullable=True),
        sa.Column('block_creation', sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('contract_address'),
    )
    op.create_index(op.f('ix_tokens_name'), 'tokens', ['name'], unique=False)
    op.create_table(
        'token_transfers',
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False
        ),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('seller_address', sa.String(length=128), nullable=True),
        sa.Column('buyer_address', sa.String(length=128), nullable=True),
        sa.Column('amount', sa.Integer(), nullable=False),
        sa.Column('number_transactions', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['buyer_address'], ['hodlers.address'],),
        sa.ForeignKeyConstraint(['seller_address'], ['hodlers.address'],),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_transfers')
    op.drop_index(op.f('ix_tokens_name'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_hodlers_address'), table_name='hodlers')
    op.drop_table('hodlers')
    # ### end Alembic commands ###
